#cloud-config
chpasswd:
  list: |
    root:${tmos_admin_password}
    admin:${tmos_admin_password}
  expire: False
tmos_dhcpv4_tmm:
  enabled: true
  rd_enabled: false
  configsync_interface: 1.1
  default_route_interface: 1.3
  dhcp_timeout: 120
  inject_routes: false
  icontrollx_trusted_sources: false
  do_enabled: false
  as3_enabled: false